### ISSUE TITLE
Add keystone plugin

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rz-pm#29]
- either make keystone lib a dependency somehow or modify the plugin to embed it during build time

**Comment by ret2libc** [comment]
If we choose to have a "sys-keystone" plugin which is just used to check if "keystone" is installed on the system, we could use pkg-config/cmake to check the presence.

**Comment by wargio** [comment]
can't we do like for capstone?

**Comment by wargio** [comment]
or even better support custom options, and have special flags for each plugin

**Comment by ret2libc** [comment]
> can't we do like for capstone?
> 
> 

What do you mean exactly? Please consider that what I'm trying to come up with here is not a solution that is specific to keystone only but that works in general for other plugins that may require a system library/program to run

**Comment by wargio** [comment]
what i meant is like have custom flag to allow the user to use the system lib or download it as a missing dependency like we do for capstone

**Comment by ret2libc** [comment]
Done
