### ISSUE TITLE
Can't compile jsdec on MacOS

### ISSUE THREAD

**Issue by palmerj** [rizinorg/rz-pm#32]
```
❯ rz-pm --debug install jsdec
2022/12/30 23:15:11 Updating rz-pm-db repository...
Building jsdec...
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.
ninja: Entering directory `build'
[1/2] Compiling C object libcore_pdd.dylib.p/core_pdd.c.o
FAILED: libcore_pdd.dylib.p/core_pdd.c.o
ccache cc -Ilibcore_pdd.dylib.p -I. -I.. -I../duktape -I/usr/local/Cellar/rizin/0.4.1/include/librz -I/usr/local/Cellar/rizin/0.4.1/include/librz/sdb -fcolor-diagnostics -Wall -Winvalid-pch -g '-DJSDEC_HOME="/usr/local/lib/rizin/plugins/jsdec"' -DUSE_JSC -MD -MQ libcore_pdd.dylib.p/core_pdd.c.o -MF libcore_pdd.dylib.p/core_pdd.c.o.d -o libcore_pdd.dylib.p/core_pdd.c.o -c ../core_pdd.c
In file included from ../core_pdd.c:8:
In file included from /usr/local/Cellar/rizin/0.4.1/include/librz/rz_cmd.h:5:
/usr/local/Cellar/rizin/0.4.1/include/librz/rz_util.h:22:10: fatal error: 'openssl/bn.h' file not found
#include <openssl/bn.h>
         ^~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
exit status 1
```

I have openssl@3 installed via brew and have set the env variables as brew won't link:

```
export PATH="/usr/local/opt/openssl@3/bin:$PATH
export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
```

```
❯ brew link --force openssl
Warning: Refusing to link macOS provided/shadowed software: openssl@3
If you need to have openssl@3 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@3/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@3 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@3/include"

For pkg-config to find openssl@3 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@3/lib/pkgconfig"
```

**Comment by wargio** [comment]
looks like you have a broken installation of rizin, can you try to uninstall and reinstall it? and then try to install jsdec?

**Comment by wargio** [comment]
no, i think there are some changes on openssl side which broke the include, but that is weird that you didn't have this issue before

**Comment by ret2libc** [comment]
@wargio I don't see `openssl` requested in the `meson.build` file of jsdec plugin.  That could be the reason. You should `dependency('openssl')` and then use it in the `depends` of the right targets. Could that be the problem?

**Comment by ret2libc** [comment]
Something changed indeed, as the rz-pm tests don't pass anymore on my local machine either.

**Comment by ret2libc** [comment]
> Something changed indeed, as the rz-pm tests don't pass anymore on my local machine either.

However it apparently depends on the environment, because https://github.com/rizinorg/rz-pm/actions/runs/3821781197/jobs/6501271914 works.



> @wargio I don't see `openssl` requested in the `meson.build` file of jsdec plugin. That could be the reason. You should `dependency('openssl')` and then use it in the `depends` of the right targets. Could that be the problem?

Sorry, I just realize the OpenSSL inclusion is in Rizin itself. I will check.

**Comment by ret2libc** [comment]
@palmerj please follow these steps to fix it:
```
rm -rf /Users/<youruser>/Library/Application Support/rz-pm/site/artifacts/jsdec
export PATH="/usr/local/opt/openssl@3/bin:$PATH
export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
rz-pm --debug install jsdec
```

the `PKG_CONFIG_PATH` var is important as that's what we use to discover dependnecies.


I created the following to improve the situation, and I'm closing this.
- https://github.com/rizinorg/rz-pm/issues/33
- https://github.com/rizinorg/rz-pm/issues/34
- https://github.com/rizinorg/rz-pm/issues/35

Please re-open if the above does not work. Thanks for your report!

**Comment by wargio** [comment]
is that rz-pm a script?

**Comment by ret2libc** [comment]
@palmerj did you do the following?

```
rm -rf /Users/<youruser>/Library/Application Support/rz-pm/site/artifacts/jsdec
export PATH="/usr/local/opt/openssl@3/bin:$PATH
export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
rz-pm --debug install jsdec
```

**Comment by ret2libc** [comment]
Sorry, get the right values for those variables by running `brew info openssl`. It should give the right values for your system.

**Comment by ret2libc** [comment]
The message "Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate." means that actually the old build directory is still there.

Run `find ~ -path "*/rz-pm/site/artifacts" 2>/dev/null` to find the right path to delete.

The tool is still in early dev, thus the pain :) Hopefully I'll make it better soon!

**Comment by ret2libc** [comment]
Perfect! Glad it helped ;)
