### ISSUE TITLE
Windows build URL

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rz-pm#6]
Currently `rz-pm` has the code like this for installing Rizin for Windows, but surely it should be switched to use either GitHub releases or AppVeyor artifacts:
```go
func (s Site) InstallRizin(prefix, version string) error {
	url := fmt.Sprintf("http://radare.mikelloc.com/get/%s/rizin-msvc_64-%s.zip", version, version)

	fd, err := ioutil.TempFile("", "rz-pm_*.zip")
	if err != nil {
		return fmt.Errorf("could not create a temporary file: %v", err)
	}
	defer fd.Close()
```
See [`pkg/site/rizin_windows.go`](https://github.com/rizinorg/rz-pm/blob/master/pkg/site/rizin_windows.go)

**Comment by wargio** [comment]
Probably this one should be just a package as the others and not hardcoded.
So if rz-pm does not find rizin then should prompt an error which says that it cannot find rizin and to define it via an ENV variable or install it via rz-pm install rizin

the env var can be defined like this
```
setx RZPM_RIZIN "C:\path\to\rizin"
rz-pm.exe install <package name>
```

**Comment by ret2libc** [comment]
There is a brief mention of this "package" in https://github.com/rizinorg/rz-pm/blob/master/docs/rizin.md .
